country_mapping = {
    "Democratic People's Republic of Korea" : "Korea (Democratic People's Republic of)",
    'Democratic Republic of the Congo' : 'Congo, Democratic Republic of the',
    'Republic of Korea' : 'Korea, Republic of',
    'Republic of Moldova' : 'Moldova, Republic of',
    'United Kingdom' : 'United Kingdom of Great Britain and Northern Ireland',
    'United Republic of Tanzania' : 'Tanzania, United Republic of',
    'United States' : 'United States of America'}

art_mapping = {'Bolivia(PlurinationalStateof)' : 'Bolivia (Plurinational State of)',
 'BosniaandHerzegovina' : 'Bosnia and Herzegovina',
 'BruneiDarussalam' : 'Brunei Darussalam',
 'BurkinaFaso' : 'Burkina Faso',
 'CaboVerde' : 'Cabo Verde',
 'CentralAfricanRepublic' : 'Central African Republic',
 'CostaRica' : 'Costa Rica',
 "Côted'Ivoire" : "Côte d'Ivoire",
 "DemocraticPeople'sRepublicofKorea" : "Korea (Democratic People's Republic of)",
 'DemocraticRepublicoftheCongo' : 'Congo, Democratic Republic of the',
 'DominicanRepublic' : 'Dominican Republic',
 'ElSalvador' : 'El Salvador',
 'EquatorialGuinea' : 'Equatorial Guinea',
 'Iran(IslamicRepublicof)' : 'Iran (Islamic Republic of)',
 "LaoPeople'sDemocraticRepublic" : "Lao People's Democratic Republic",
 'NewZealand' : 'New Zealand',
 'NorthMacedonia' : 'North Macedonia',
 'PapuaNewGuinea' : 'Papua New Guinea',
 'RepublicofKorea' : 'Korea, Republic of',
 'RepublicofMoldova' : 'Moldova, Republic of',
 'RussianFederation' : 'Russian Federation',
 'SaoTomeandPrincipe' : 'Sao Tome and Principe',
 'SaudiArabia' : 'Saudi Arabia',
 'SierraLeone' : 'Sierra Leone',
 'SouthAfrica' : 'South Africa',
 'SouthSudan' : 'South Sudan',
 'SriLanka' : 'Sri Lanka',
 'SyrianArabRepublic' : 'Syrian Arab Republic',
 'TrinidadandTobago' : 'Trinidad and Tobago',
 'UnitedArabEmirates' : 'United Arab Emirates',
 'UnitedKingdom' : 'United Kingdom of Great Britain and Northern Ireland',
 'UnitedRepublicofTanzania' : 'Tanzania, United Republic of',
 'UnitedStates' : 'United States of America',
 'Venezuela(BolivarianRepublicof)' : 'Venezuela (Bolivarian Republic of)',
 'VietNam' : 'Viet Nam'}